"""Snapshot numeric evidence without executing submissions or loading pickle."""
import sys,json,csv,hashlib,shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];LAB=Path(__file__).resolve().parents[1]
RUNS=Path('/Users/home/Downloads/runs');AUDIT=ROOT/'output/scicode2/run_evaluation'

def main():
    sources=[AUDIT/'REPORT.md',AUDIT/'reported_boundaries.json',AUDIT/'matched_comparison.json',AUDIT/'matched_failure_flags.json',AUDIT/'AUDIT_MANIFEST.json',AUDIT/'run_inventory.json',AUDIT/'extreme_prior_check.json']
    for name in ['explore','calib','cuts1','cuts2','cuts3']:
        sources.append(RUNS/'anthropic__claude-opus-5-5/run_03/data'/f'{name}.jsonl')
    sources.extend([RUNS/'anthropic__claude-opus-5-5/run_03/data/thresholds.json',RUNS/'anthropic__claude-opus-5-5/run_03/data/boundary_table.md',RUNS/'anthropic__claude-fable-5-1/run_03/data/ler_table.csv',RUNS/'anthropic__claude-fable-5-1/run_03/data/chi_check_L20.txt',RUNS/'openai__gpt-6-astra/run_01/data/ler.csv'])
    dest=LAB/'data/inherited';dest.mkdir(exist_ok=True);provenance=[]
    for p in sources:
        if not p.is_file():raise FileNotFoundError(p)
        name='audit_'+p.name if p.is_relative_to(AUDIT)else '_'.join(p.relative_to(RUNS).parts[:-1]).replace('_data','')+'_'+p.name
        target=dest/name;shutil.copyfile(p,target)
        provenance.append({'source':str(p),'snapshot':str(target.relative_to(LAB)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size,'cohort':'inherited; not generated by Lab 009'})
    # Deduplicated method-level boundary table, retaining each study separately.
    curves=json.loads((AUDIT/'reported_boundaries.json').read_text());rows=[]
    for curve in curves:
        for p,q in curve['points']:
            valid=0<=p<=.5 and 0<=q<=1
            rows.append({'study':curve['name'],'family':curve['family'],'p':p,'q':q,'status':'reported_estimate'if valid else'rejected_out_of_domain','source':curve['source']})
    with (LAB/'data/reported-boundaries.csv').open('w',newline='')as f:
        writer=csv.DictWriter(f,fieldnames=list(rows[0]));writer.writeheader();writer.writerows(rows)
    # Numeric-vector archive of inherited unconditional ML trials by cell.
    cells={}
    for name in ['explore','calib','cuts1','cuts2','cuts3']:
        path=RUNS/'anthropic__claude-opus-5-5/run_03/data'/f'{name}.jsonl'
        for line in path.read_text().splitlines():
            r=json.loads(line);key=(r['L'],r['p'],r['q']);a=cells.setdefault(key,dict(L=r['L'],p=r['p'],q=r['q'],n=0,fails=0,rb_sum=0.,rb_sumsq=0.,seconds=0.))
            for k in ['n','fails','rb_sum','rb_sumsq']:a[k]+=r[k]
            a['seconds']+=r['secs']
    rows=list(cells.values())
    for r in rows:r['ler_direct']=r['fails']/r['n'];r['ler_rb']=r['rb_sum']/r['n'];r['se_rb']=(max(r['rb_sumsq']/r['n']-r['ler_rb']**2,0)/(r['n']-1))**.5
    with (LAB/'data/inherited-ml-cells.csv').open('w',newline='')as f:
        writer=csv.DictWriter(f,fieldnames=list(rows[0]));writer.writeheader();writer.writerows(rows)
    import numpy as np
    np.savez_compressed(LAB/'data/inherited-ml-vectors.npz',**{k:np.array([r[k]for r in rows])for k in rows[0]})
    for p in [LAB/'data/reported-boundaries.csv',LAB/'data/inherited-ml-cells.csv',LAB/'data/inherited-ml-vectors.npz']:
        provenance.append({'snapshot':str(p.relative_to(LAB)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'cohort':'derived from inherited numerical evidence'})
    result={'status':'complete','records':provenance,'inherited_ml_trials':sum(r['n']for r in rows),'ml_cells':len(rows),'boundary_curves':len(curves),'new_trials':0,'pooling':'raw chunks aggregated only within one identical decoder/source campaign; studies remain separate in boundary table','formats':'CSV/JSON/JSONL/NPZ numeric only; no binary caches'}
    (LAB/'results/data-provenance.json').write_text(json.dumps(result,indent=2)+'\n');print({k:v for k,v in result.items()if k!='records'})

if __name__=='__main__':main()
